--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/str0nixofficial/SelfDamageBlocker_v1.0.0
build-by-default: true
branches:
- master
projects:
  SelfDamageBlocker_v1.0.0:
    path: ""
...
